name: Build and publish image to docker hub
on:
    [workflow_dispatch]
jobs:
    publish_image:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3         
            
            - name: Build
              uses: docker/build-push-action@v6
              with:
                platforms: linux/amd64,linux/arm64
                tags: ciaa/mlops:latest
                secrets: |
                  "aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}"
                  "aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
            
            - name: push image to docker hub
              run: |
                docker login -u ciaa -p ${{ secrets.DOCKER_HUB_TOKEN }}
                docker push ciaa/mlops:latest
