name: Build and publish image to docker hub
on:
    [workflow_dispatch]
jobs:
    publish_image:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3         
            
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_HUB_USERNAME }}
                password: ${{ secrets.DOCKER_HUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                context: .
                push: true
                tags: ciaa/mlops:latest
                secrets: |
                  aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}

    deploy_to_k8s:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Set up kubectl
            uses: azure/k8s-set-context@v4
            with:
              kubeconfig: ${{ secrets.KUBECONFIG }}

          - name: Deploy
            uses: Azure/k8s-deploy@v5
            with:
              action: deploy
              namespace: 'default'
              manifests: |
                  k8s/deploy_app.yaml